Milestone 2
taiwo2/Calculator pull request #4
Opened 2021-06-02 10:08 UTC by taiwo2

2021-06-02 13:55 UTC, bellom requested changes
## Hi @\ :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-06-02 13:55 UTC, bellom commented on src/components/ButtonPanel.js
> +        <Button name="=" />
### [Optional]
Your code appears to be WET-(Write Every Time), Microverse encourage DRY-(Don't Repeat Yourself) code, In other words; you repeated the `Button` component multiple times.

You can use [objects.key](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys)  and `map` to loop through the objects. `objects.keys` for the outer loop and `map` for the inner loop.

Example; 
```
const GroupButtons = {
  Group 1: ['AC', '+/-', '%', '÷'],
  Group 2: ['7', '8', '9', 'X'],
   ............
}
```
OR

[Creating a two-dimensional array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#creating_a_two-dimensional_array) and implement nested loop with a map.
EXample;
```
  const buttons = [
    ['AC', '+/-', '%', '÷'],
    ['7', '8', '9', 'X'],
    ..........
  ];
```

2021-06-02 13:55 UTC, bellom commented on src/components/Display.js
> +  result: 0,
This defaultProps should be a string, as you specified on line 14.
That is; `result: '0'`

2021-06-03 04:04 UTC, afanimartin approved these changes
## Approved ✅ ✅ ✅ 
Nice work making the requested change. 
Merge and proceed to the next milestone.

### Martin Afani
#### Slack: whiz25

2021-06-04 07:44 UTC, merged